name: Update README.md

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test update readme
      run: |
        npm install
        npm run update
      env:
        CI: true
    - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply readme changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
